# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean verify -P cuke
#     - uses: deblockt/cucumber-report-annotations-action@v1.7
#       with:
#         access-token: ${{ secrets.GITHUB_TOKEN }}
#         path: "**/test-output/Json/ExtentJson.json"
    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: ./test-output/Spark
#     - name: HTML Preview
#       uses: pavi2410/html-preview-action@v2
#       with:
#        html_file: # default is index.html
#     - name: Deploy report page to GitHub Page
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./test-output/spark
#     - name: Deploy to GitHub Pages
#       if: success()
#       uses: crazy-max/ghaction-github-pages@v2
#       with:
#         target_branch: gh-pages
#         build_dir: ./test-output/Spark
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



